_G.INTERNAL_HOOK_INTERFACE.TrackRemote:Fire("Pets_LocalPetsUnequipped")
_G.INTERNAL_HOOK_INTERFACE.TrackRemote:Fire("Pets_LocalUnequipAll")
_G.INTERNAL_HOOK_INTERFACE.TrackRemote:Fire("Pets_GetEquipped")
_G.INTERNAL_HOOK_INTERFACE.PerformCallAndGenerateLog:Fire(function(Network)
    return Network.Invoke("Pets_GetEquipped")
end)
